=== 2gplus/widgets-resources/xsd/widget.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.mendix.com/widget/1.0/"
           xmlns="http://www.mendix.com/widget/1.0/"
           elementFormDefault="qualified">

    <xs:element name="widget" type="widgetType"/>

    <xs:complexType name="widgetType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="icon" type="xs:base64Binary" minOccurs="0"/>
            <xs:element name="phonegap" type="phonegapType" minOccurs="0"/>
            <xs:element name="properties" type="propertiesType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="needsEntityContext" type="xs:boolean" use="required"/>
        <xs:attribute name="pluginWidget" type="xs:boolean"/>
        <xs:attribute name="mobile" type="xs:boolean" default="false"/>
        <xs:attribute name="supportedPlatform" type="platformType" default="All"/>
        <xs:attribute name="offlineCapable" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="phonegapType">
        <xs:attribute name="enabled" type="xs:boolean" use="required"/>
    </xs:complexType>

    <xs:complexType name="propertiesType">
        <xs:choice>
            <xs:sequence>
                <xs:element name="propertyGroup" type="propertyGroupType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
                    <xs:element name="systemProperty" type="systemPropertyType" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="propertyGroupType">
        <xs:complexContent>
            <xs:extension base="propertiesType">
                <xs:attribute name="caption" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="propertyType">
        <xs:sequence>
            <xs:element name="caption" type="xs:string"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="attributeTypes" type="attributeTypesType" minOccurs="0"/>
            <xs:element name="enumerationValues" type="enumerationValuesType" minOccurs="0"/>
            <xs:element name="properties" type="propertiesType" minOccurs="0"/>
            <xs:element name="returnType" type="returnTypeType" minOccurs="0"/>
            <xs:element name="translations" type="translationsType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string" use="required"/>
        <xs:attribute name="type" type="propertyTypeType" use="required"/>
        <xs:attribute name="isList" type="xs:boolean" default="false"/>
        <xs:attribute name="entityProperty" type="xs:string"/>
        <xs:attribute name="allowNonPersistableEntities" type="xs:boolean" default="false"/>
        <xs:attribute name="isPath" type="isPathType" default="no"/>
        <xs:attribute name="pathType" type="pathTypeType"/>
        <xs:attribute name="parameterIsList" type="xs:boolean" default="false"/>
        <xs:attribute name="multiline" type="xs:boolean" default="false"/>
        <xs:attribute name="defaultValue" type="xs:string" default=""/>
        <xs:attribute name="required" type="xs:boolean" default="true"/>
        <xs:attribute name="isDefault" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:simpleType name="propertyTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="action"/>
            <xs:enumeration value="attribute"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="enumeration"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="object"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="textTemplate"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="attributeTypesType">
        <xs:sequence>
            <xs:element name="attributeType" type="attributeTypeType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="attributeTypeType">
        <xs:attribute name="name" type="attributeTypeNameType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="attributeTypeNameType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AutoNumber"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Currency"/>
            <xs:enumeration value="DateTime"/>
            <xs:enumeration value="Enum"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="HashString"/>
            <xs:enumeration value="Integer"/>
            <xs:enumeration value="Long"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Decimal"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="isPathType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="no"/>
            <xs:enumeration value="optional"/>
            <xs:enumeration value="yes"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="pathTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="reference"/>
            <xs:enumeration value="referenceSet"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="enumerationValuesType">
        <xs:sequence>
            <xs:element name="enumerationValue" type="enumerationValueType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="enumerationValueType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="key" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="returnTypeType">
        <xs:attribute name="type" type="returnTypeTypeType" use="required"/>
        <xs:attribute name="isList" type="xs:boolean" default="false"/>
        <xs:attribute name="entityProperty" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="returnTypeTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Void"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Integer"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="DateTime"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Object"/>
            <xs:enumeration value="Decimal"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="translationsType">
        <xs:sequence>
            <xs:element name="translation" type="translationType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="translationType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="platformType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="All"/>
            <xs:enumeration value="Native"/>
            <xs:enumeration value="Web"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="systemPropertyType">
        <xs:sequence>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="key" type="systemPropertyKey" use="required"/>
    </xs:complexType>

    <xs:simpleType name="systemPropertyKey">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Label"/>
            <xs:enumeration value="Name"/>
            <xs:enumeration value="TabIndex"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== 2gplus/widgets-resources/packages/feedback/src/Feedback.xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.mendix.widget.native.feedback.Feedback" supportedPlatform="Native" needsEntityContext="true" offlineCapable="true" pluginWidget="true" xmlns="http://www.mendix.com/widget/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mendix.com/widget/1.0/ ../../../xsd/widget.xsd">
    <name>Feedback</name>
    <description>Widget to send feedback and collaborate with others on your Mendix Project</description>
    <icon>/9j/4QAYRXhpZgAASUkqAAgAAAAAAAAAAAAAAP/sABFEdWNreQABAAQAAABkAAD/7gAOQWRvYmUAZMAAAAAB/9sAhAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgICAgICAgICAgIDAwMDAwMDAwMDAQEBAQEBAQIBAQICAgECAgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwP/wAARCAAQABADAREAAhEBAxEB/8QAbQAAAwEAAAAAAAAAAAAAAAAAAgMECgEAAgMAAAAAAAAAAAAAAAAABQYBAwcQAAICAwEBAAMAAAAAAAAAAAMFBAYBAgcRCBMUFxEAAgICAQMEAwEAAAAAAAAAAQIDBAUGERIiEwAhIwcxQhQV/9oADAMBAAIRAxEAPwDZH37uT/nTyorYiUi/pRXpv5tXJzaKCnfQkHMfywcwRWY2Qgr/AEeSvxiWsjMgx/WEUWgSSAkL6lZ7N2qNqGCOMpkvITCrMBFbXjvhWT9JeO5A4HeoALKT6ynctsyGHv1asEJjz5mJqxs4FfIpx8tVJvxFZK8SRLKq/IihTIrN6Hgva7beHtnUtq8Zh1EjaPL6QggNI5aL89KNxb4rHMnFq0/KGy9DjrcZlso6wEj1jKNqUkYAw+abjdLzuN1iHb92ZKDZRTJUrc+SaSIeydCDgLEPy88pQO5bxLIAAAWmfZNnYdhvYClA13Zq84GQ6HAo4gcfFSksEHz3QnfLFXjkIldhK0CBPTu6fNZ+lvkM9c5f63ttPkr9utzpAZE3iVAyLBLMPjabI9K/VL9bA4ErjttYpmYgnNIJIJ+voLadLr6zhdhO67FXjyeRoIWqV7HfC07e0fVEOFEMXvLL+8pVImfpckX/AGV9eZHbvFj8Xat18ndkMc2RVgJcdRA5nXHDjx17lnsrxzhDKiPJMXYxKpl4T8ySucWF22dvLAXpCWZGUf2RbIFDl915zpqQtTF2hDgZK1a7/UY2xVUprtEEzIOOKUKSLErcWr1t29rnqsccMUH+POpf+JlJWhZ5+X+F+RJBXlPEqQq5hBZo2jbxhvQ367+pn1O/NNZntDZKrrGMmj8Pl6XHwf6sZBhtXYB1V5LLRiwwRJkmTzMg/9k=</icon>
    <properties>
        <propertyGroup caption="General">
            <propertyGroup caption="General">
                <property key="sprintrapp" type="string">
                    <caption>App ID</caption>
                    <description>The App ID is a hash that uniquely identifies your app project. You can find this ID in Settings > General in the Developer Portal.</description>
                </property>
                <property key="allowScreenshot" type="boolean" defaultValue="true">
                    <caption>Allow screenshots</caption>
                    <description>If you are not allowed to send screenshots when submitting feedback (for legal reasons, etc.), set this to ‘No’.</description>
                </property>
            </propertyGroup>
            <propertyGroup caption="Branding">
                <property key="logo" type="image" required="false">
                    <caption>Logo</caption>
                    <description>For customized branding, add a logo to the widget. The recommended size of the image is 90 by 90 pixels.</description>
                </property>
            </propertyGroup>
            <propertyGroup caption="Common">
                <systemProperty key="Name"/>
            </propertyGroup>
        </propertyGroup>
    </properties>
</widget>
