=== 2gplus/widgets-resources/xsd/widget.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.mendix.com/widget/1.0/"
           xmlns="http://www.mendix.com/widget/1.0/"
           elementFormDefault="qualified">

    <xs:element name="widget" type="widgetType"/>

    <xs:complexType name="widgetType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="icon" type="xs:base64Binary" minOccurs="0"/>
            <xs:element name="phonegap" type="phonegapType" minOccurs="0"/>
            <xs:element name="properties" type="propertiesType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="needsEntityContext" type="xs:boolean" use="required"/>
        <xs:attribute name="pluginWidget" type="xs:boolean"/>
        <xs:attribute name="mobile" type="xs:boolean" default="false"/>
        <xs:attribute name="supportedPlatform" type="platformType" default="All"/>
        <xs:attribute name="offlineCapable" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="phonegapType">
        <xs:attribute name="enabled" type="xs:boolean" use="required"/>
    </xs:complexType>

    <xs:complexType name="propertiesType">
        <xs:choice>
            <xs:sequence>
                <xs:element name="propertyGroup" type="propertyGroupType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
                    <xs:element name="systemProperty" type="systemPropertyType" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="propertyGroupType">
        <xs:complexContent>
            <xs:extension base="propertiesType">
                <xs:attribute name="caption" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="propertyType">
        <xs:sequence>
            <xs:element name="caption" type="xs:string"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="attributeTypes" type="attributeTypesType" minOccurs="0"/>
            <xs:element name="enumerationValues" type="enumerationValuesType" minOccurs="0"/>
            <xs:element name="properties" type="propertiesType" minOccurs="0"/>
            <xs:element name="returnType" type="returnTypeType" minOccurs="0"/>
            <xs:element name="translations" type="translationsType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string" use="required"/>
        <xs:attribute name="type" type="propertyTypeType" use="required"/>
        <xs:attribute name="isList" type="xs:boolean" default="false"/>
        <xs:attribute name="entityProperty" type="xs:string"/>
        <xs:attribute name="allowNonPersistableEntities" type="xs:boolean" default="false"/>
        <xs:attribute name="isPath" type="isPathType" default="no"/>
        <xs:attribute name="pathType" type="pathTypeType"/>
        <xs:attribute name="parameterIsList" type="xs:boolean" default="false"/>
        <xs:attribute name="multiline" type="xs:boolean" default="false"/>
        <xs:attribute name="defaultValue" type="xs:string" default=""/>
        <xs:attribute name="required" type="xs:boolean" default="true"/>
        <xs:attribute name="isDefault" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:simpleType name="propertyTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="action"/>
            <xs:enumeration value="attribute"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="enumeration"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="object"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="textTemplate"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="attributeTypesType">
        <xs:sequence>
            <xs:element name="attributeType" type="attributeTypeType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="attributeTypeType">
        <xs:attribute name="name" type="attributeTypeNameType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="attributeTypeNameType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AutoNumber"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Currency"/>
            <xs:enumeration value="DateTime"/>
            <xs:enumeration value="Enum"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="HashString"/>
            <xs:enumeration value="Integer"/>
            <xs:enumeration value="Long"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Decimal"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="isPathType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="no"/>
            <xs:enumeration value="optional"/>
            <xs:enumeration value="yes"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="pathTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="reference"/>
            <xs:enumeration value="referenceSet"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="enumerationValuesType">
        <xs:sequence>
            <xs:element name="enumerationValue" type="enumerationValueType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="enumerationValueType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="key" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="returnTypeType">
        <xs:attribute name="type" type="returnTypeTypeType" use="required"/>
        <xs:attribute name="isList" type="xs:boolean" default="false"/>
        <xs:attribute name="entityProperty" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="returnTypeTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Void"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Integer"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="DateTime"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Object"/>
            <xs:enumeration value="Decimal"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="translationsType">
        <xs:sequence>
            <xs:element name="translation" type="translationType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="translationType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="platformType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="All"/>
            <xs:enumeration value="Native"/>
            <xs:enumeration value="Web"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="systemPropertyType">
        <xs:sequence>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="key" type="systemPropertyKey" use="required"/>
    </xs:complexType>

    <xs:simpleType name="systemPropertyKey">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Label"/>
            <xs:enumeration value="Name"/>
            <xs:enumeration value="TabIndex"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== 2gplus/widgets-resources/packages/qr-code/src/QRCode.xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.mendix.widget.native.qrcode.QRCode" supportedPlatform="Native" needsEntityContext="true" offlineCapable="true" pluginWidget="true" xmlns="http://www.mendix.com/widget/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mendix.com/widget/1.0/ ../../../xsd/widget.xsd">
    <name>QR code</name>
    <description>Displays a QR code</description>
    <icon>iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAIVJREFUWEftlNEKwCAIRXX//8+tYhMmSN0YKOKB6CEmeqYyEbV+YFr7fsY8QuFcz+2GGNAVWbyVWgbQOPEMWP9Sv68M7MZxN1AJVAKjFWdb6q622J2CFWGmQAygWAZQ/A30So4M/EWNYZ4pOCWOAXSD5TVgbTT9nsZAJVAJ1B4QAyhJDBDdQaBQGZb6/OEAAAAASUVORK5CYII=</icon>
    <properties>
        <propertyGroup caption="Data source">
            <propertyGroup caption="QR code value">
                <property key="value" type="attribute" required="false">
                    <caption>Dynamic value</caption>
                    <description>Value of the QR code that will be displayed.</description>
                    <attributeTypes>
                        <attributeType name="String"/>
                    </attributeTypes>
                </property>
                <property key="defaultValue" type="string" required="false">
                    <caption>Static value</caption>
                    <description>Used when no dynamic value is provided.</description>
                </property>
            </propertyGroup>
        </propertyGroup>
    </properties>
</widget>

=== 2gplus/widgets-resources/packages/rating/src/Rating.xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.mendix.widget.native.rating.Rating" supportedPlatform="All" needsEntityContext="true" offlineCapable="true" pluginWidget="true" xmlns="http://www.mendix.com/widget/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mendix.com/widget/1.0/ ../../../xsd/widget.xsd">
    <name>Rating</name>
    <description>This widget lets users give a rating</description>
    <icon>iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAABNJJREFUeAHtWktrFEEQ7prdmAmKgh5UVPTi6yIoguBBPChoHsaDIiiiooiPg79ACZ58nDz4QBAFwYsKmqyJ4MWDl4B3X3gQXycRwZCN2e22Kto49M7M9is9SdyFpad7qqvq+7qqeugZxlq/FgMtBv5nBqAo8N0Do1trHK6T/XIkTlZ6Op4X4UtUhFEhBNTr7A4TYg39a3W4TWNF+FIIAT2V8XWCseX/AIsVNPavH+6qEAI451tViGljqsxk9AshQAjWQEDa2GQAVnUGJ4ByXTCxRXWExoqoA8EJ+Jvr81UCsD+/iDoQnIC8XM+7l0KYl6HgBOTlet49L2hTlAQlICv/pV9F1IGgBOTkv+QgeB0ISoBOjuvISLZ8tEEJ0MlxHRkfwKWOYAQ0y3/pUOg6EIwAjfyXHAStA8EIMMltE1nJmm0bjACT3DaRtQUu5wUhQDf/pVMh60AQAgzyX3IQrA4EIcAmp23mSPZM2nKacPeAWCJgfFHaPZsxXuddpvPwxKirq/Lrhem8LPlSve1rfy98Ue83nMN1Pq6e4Ixdw7O6hnvq5GnVBxAY7qcGe+MbSb8bUoAzcXbGgSfEuKAT2JLo8bqBAFz2j4rMjOmmYWsggLXBAWDwasag/gtkAhNiU3E1EDDUGb9fOK99AwO4jJPq6oTp1p/AgFgIE2FT/c8tdJ2Pfm3iwP+8wFBnToc+wOtIRIcHd88aznK3IQKSgjRx0dz29QBwaTpFA/lKPpPveeAJa24EJMmgaBCM38bH1LXJ8al2jeBfAYuONAMu/c6NAClELSmkPJqq0SBXnXzUBU+4tCOAhOVvqkWD6apLHNRqR0By0lSJBrnqbFbzXE/6n7y2ioCkgqKiwWXVk/5bRUBSQeho8LHqSf+dI0Aq2/tMzPs5MvYVd4kOOTYZLRIwOmd2++L72+GHD/3OESCd+Dk6tm+ywZMtskG2pF3X1hsBgovDrs7ozvdpy0sKdD6pruLj4o0uAB9yURusHuyK37rq8hIBvBZu9SVgXzadCegTIsJPPg5Kx0K1ZJNsu9pzVjBcGduG53dLXR0xnU82ybbpPFXemQCfBUl1rlnfh22nIhhq788iwsczgVMEuO79AOwl/bMANhv38UzgRIBtCOLKcfxfXLYk3kx/uqaxZoDT7tv6IHVZp4Dt3o8GP5VK7KD6cTR9PI3fD9+1KaguzwTWEWCzD+MqP4zK8ToVPK0GjdE9kpGro9va+CJ1W0UA7b/Dj6sftFcLYISBOPN0V8ctaTiv3dE/epQJuIIvM2bnycl7FFWbeuPlfWCeRlYRYLL3U5ErR2y9LngCRbI0R7dAujwTWBGgU3ioqEURu0BFrtITv5OrpdvSHJpLOnQKpI5PabaNU0Bn788qdGkO6IzpFEgkyeqcwDgCmu39eGr8IKvQ6YBNk9EpkLbPBMYEZIYaFjrM2aNDvfHeJ93wPQ2IyxjpHNod78Fj3GP42m4kTRf6dihtPG/MKAXow4lavfpJVUjFqhTBfptcV3Xp9LsHqivrXNzDj6k2qvLlUry00gOf1fGsvnEEIPs1qcy10Ek9pm1mgUz4pqvTKAJI6c7+6nHcn8/jO5VvpUicTnuo0TXuQ26iQHK4iqeFC3Bxzg3tim/60NvS0WKgxcD/wcBvI6ARwApK+xMAAAAASUVORK5CYII=
    </icon>
    <properties>
        <propertyGroup caption="Data source">
            <property key="rating" type="attribute">
                <caption>Rating value</caption>
                <description/>
                <attributeTypes>
                    <attributeType name="Integer"/>
                    <attributeType name="Long"/>
                    <attributeType name="Decimal"/>
                </attributeTypes>
            </property>
            <property key="maximumValue" type="integer" defaultValue="5">
                <caption>Maximum value</caption>
                <description/>
            </property>
            <property key="fractions" type="integer" defaultValue="0">
                <caption>Fractions</caption>
                <description>The number of decimal places for the rating value. Must be between 0 and 20.</description>
            </property>
            <property key="editable" type="enumeration" defaultValue="default">
                <caption>Editable</caption>
                <description/>
                <enumerationValues>
                    <enumerationValue key="default">Default</enumerationValue>
                    <enumerationValue key="never">Never</enumerationValue>
                </enumerationValues>
            </property>
        </propertyGroup>

        <propertyGroup caption="Events">
            <property key="onChange" type="action" required="false">
                <caption>On change</caption>
                <description/>
            </property>
        </propertyGroup>

        <propertyGroup caption="Appearance">
            <property key="icon" type="enumeration" defaultValue="star">
                <caption>Icon</caption>
                <description/>
                <enumerationValues>
                    <enumerationValue key="star">Star</enumerationValue>
                    <enumerationValue key="heart">Heart</enumerationValue>
                    <enumerationValue key="rocket">Rocket</enumerationValue>
                    <enumerationValue key="bell">Bell</enumerationValue>
                </enumerationValues>
            </property>
            <property key="iconSize" type="integer" defaultValue="50">
                <caption>Icon size</caption>
                <description/>
            </property>
        </propertyGroup>
    </properties>
</widget>

=== 2gplus/widgets-resources/packages/barcode-scanner/src/BarcodeScanner.xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.mendix.widget.native.barcodescanner.BarcodeScanner" needsEntityContext="true" offlineCapable="true" pluginWidget="true" 
    xmlns="http://www.mendix.com/widget/1.0/" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mendix.com/widget/1.0/ ../../../xsd/widget.xsd">
    <name>Barcode scanner</name>
    <description>This widget enables native barcode scanning functionality within your Mendix mobile application.</description>
    <icon>iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAElBMVEUAAABXV1dVVVVJsPhIsPdVVVWcEer3AAAABHRSTlMASeP9eof+WwAAAHJJREFUeAHtlzEKxTAMQ239r/tfuaHtFEpxIkog6C1e7AchixQXJsET5OQ2eIMo8LDNOQE7wegTOkEMspsAJGKE/iaBjDrlG7OAf6M89xdYYIEFBb4XtPF7n/sL1v2CWYoespSY56ysFw698uilS6995gADwwwpR7MpFwAAAABJRU5ErkJggg==</icon>
    <properties>
        <property key="inputValue" type="attribute">
            <caption>Attribute</caption>
            <category>General</category>
            <description>The attribute that contains the barcode value</description>
            <attributeTypes>
                <attributeType name="String" />
            </attributeTypes>
        </property>
        <property key="onChange" type="action" required="false">
            <caption>On change action</caption>
            <category>Events</category>
            <description />
        </property>
    </properties>
</widget>

=== 2gplus/widgets-resources/packages/progress-bar/src/ProgressBar.xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.mendix.widget.native.progressbar.ProgressBar" needsEntityContext="true" offlineCapable="true" pluginWidget="true" 
    xmlns="http://www.mendix.com/widget/1.0/" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mendix.com/widget/1.0/ ../../../xsd/widget.xsd">
    <name>Progress bar</name>
    <description>Displays progress in a bar.</description>
    <icon>iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAABs1BMVEUAAAD///+AgICA//9V//+Av/9mzP9V1f9Jtv9gv/9Vxv9Ns/9duf9VVVVVv/9Jtv9Qv/9LtP9RvP9Ns/9Ruf9Osf9Osf9YWFhMs/9bW1tPuf9Ns/9NsvdLtPhMs/hKtfhLtPlVVVVNsvlIsflMs/pJsfpNs/pLtPpKsfpMs/pKsPpMs/tJsftLtPtKsftLsfdJsvdVVVVLsPhLtPhIs/hJs/hVVVVIrvZIr/VJsfhWVlZJsvhKsPhWVlZJsvhXV1dIsPhKsfhJsvlKsflKsflIsflMk8FJsvdIsfdJsPhKsvhNlslJsfhKsPhJsfhWVlZKsfhJsfdIsPdJsfdIsfdIsfhJsPhJsfhJsPhVVVVJsPhIsfhIsfhJsfdVWl5UXF9JsfdIsPdIsPdJsfdJsfhJsPhJsPhIsfhVVVVIsfhIsfhWVlZIsfhJsPhIsPhJsPdJsPdJsfdIsPdJsfdJsfdIsPdJsfhJsPhIsPhJsfhJsfhVVVVIsPhVVVVIsfhJsfhJsPhIsfhJsfhJsPhVVVVIsPhVVVVWVlZIrPBIsfhSZHBTZHBIq+9IsPdKodxOiLBVVVV1/q+UAAAAjHRSTlMAAQICAwQFBgcICQoLDAwOEBETFBYXGhobHB0eISIlJikqKy4vMTIzNDY3OTs9PkFCQkRHSk1OUmNpa21ubnBwcXV3eXx/f4SGi46Sk5Wam5ygoqepra+ztba5u77AwcPExcnKzs/S1NTX2Nnb3N/g4+Tm5+rt7u/w8fLy8/P09fb3+Pn5+vz9/v7+/kcKcD4AAAHXSURBVHgB7ZRnW9RAEICHIHbEjrFj74rllChG7D12jb17GrsgCqKiCBYC+cnuy4fVjDyc9+Trvp/e2Wdm73Yzs+IYFYfD4fCDOOnJKtCTxIEvo9EY9Wf/SX/UKP9Q6s6qoLskitaBrCoGWtXvj9SXwxODaZq+XcnSlBup4fpkfM07fA9a3xSWR3Yo5c7P/+8LvAPkda5madI1/PZUfEUH3oaCF/Rxir/vIaK+WdrIe7+WlQlX8LsN+LJ2/KD8oZkdIrH43H8g+8jrWs9K3SX8/nR8yRv8CGoJ+BZ+Lix7u8n7sIGFcRfwhzPxRa/wY5LD4x4CG8YmClvI+7SJuPYc/ng2vuAFflIUoSmJbZSY6PAPk/d5M2HNGWqezsXnPcNP14iiyZQkNqJ/v5u83q0Cp6h5Ph+d8wQ/S32eero6t4FpgC/bBI5T83IhOusRfr5WKmzAEYbSr9sFjlLzejE64wF+sQ4f8wi3TDT8bYfAIWral6IN9/DL4/GxL5HP+HOnwH5qOpaj0+7gVyeKRX9G1UjYXmo6V6lZsOhG0q0sLdR0rdOzYNGtrIdpF73wcWNuFhRqmNQ4/xoeGuzdomZBoce5+INS/Ekr9KjqZ/1mkWfd4XA4HL8B8hyYZtVVCEkAAAAASUVORK5CYII=</icon>
    <properties>
        <property key="indeterminate" type="boolean" defaultValue="false">
            <caption>Indeterminate</caption>
            <category>Value</category>
            <description>If set, the indicator will spin and the progress value will be ignored</description>
        </property>
        <property key="progressValue" type="attribute" required="false">
            <caption>Progress value</caption>
            <category>Value</category>
            <description/>
            <attributeTypes>
                <attributeType name="Integer" />
                <attributeType name="Long" />
                <attributeType name="Decimal" />
            </attributeTypes>
        </property>
        <property key="progressMax" type="attribute" required="false">
            <caption>Maximum progress value</caption>
            <category>Value</category>
            <description>Defaults to 100</description>
            <attributeTypes>
                <attributeType name="Integer" />
                <attributeType name="Long" />
                <attributeType name="Decimal" />
            </attributeTypes>
        </property>

        <property key="animated" type="boolean" defaultValue="true">
            <caption>Animated</caption>
            <category>Appearance</category>
            <description>Whether or not to animate changes to the progress value</description>
        </property>
        <property key="height" type="integer" defaultValue="6">
            <caption>Height</caption>
            <category>Appearance</category>
            <description />
        </property>
        <property key="color" type="string" required="false">
            <caption>Fill color</caption>
            <category>Appearance</category>
            <description/>
        </property>
        <property key="unfilledColor" type="string" required="false">
            <caption>Unfilled color</caption>
            <category>Appearance</category>
            <description/>
        </property>
        <property key="borderWidth" type="integer" defaultValue="1">
            <caption>Border width</caption>
            <category>Appearance</category>
            <description>Set 0 to disable</description>
        </property>
        <property key="borderColor" type="string" required="false">
            <caption>Border color</caption>
            <category>Appearance</category>
            <description/>
        </property>
        <property key="borderRadius" type="integer" defaultValue="4">
            <caption>Border radius</caption>
            <category>Appearance</category>
            <description>Rounding of corners, set to 0 to disable</description>
        </property>
    </properties>
</widget>

=== 2gplus/widgets-resources/packages/slider/src/Slider.xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.mendix.widget.native.slider.Slider" supportedPlatform="Native" needsEntityContext="true" offlineCapable="true" pluginWidget="true" xmlns="http://www.mendix.com/widget/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mendix.com/widget/1.0/ ../../../xsd/widget.xsd">
    <name>Slider</name>
    <description>Change a number value using a slider.</description>
    <icon>iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAAEvQFx7AAAAIVBMVEUAAAD///9SuP+IiIhJsfdJsfhJsfeJiYlIsPhIsPeIiIjzihhCAAAACXRSTlMAARlJZb3I4/MVTrONAAAAz0lEQVRIx2NgQAMTgJhr1qpVEBZOwAmSrZy1agEDB151IMA4E6YJg8Ewk4EqgHMqLiu4Vs5cBQQLsNnOOomB3oAxwwFVIHMmWhDMRBWwWgUUWAUFy7GpwCLgOXMmwwgGLG0CqAKRMyeih9g0AkFISKAKOV4WAwVWkRNRWARmoAtMQRXQnBnAMAqGG2CKnDlzqgIeBcAsjZEUUEAnSMEMPApmggHNFFStAucApEywCjU3mONWUEwvR0JLXIzsjwJEQQoC8cWWSEab42iapQQAAD3okfmgsuelAAAAAElFTkSuQmCC</icon>
    <properties>
        <propertyGroup caption="Data source">
            <propertyGroup caption="Current value">
                <property key="value" type="attribute">
                    <caption>Value</caption>
                    <description>The selected value on the slider</description>
                    <attributeTypes>
                        <attributeType name="Integer"/>
                        <attributeType name="Long"/>
                        <attributeType name="Decimal"/>
                    </attributeTypes>
                </property>
                <property key="editable" type="enumeration" defaultValue="default">
                    <caption>Editable</caption>
                    <description/>
                    <enumerationValues>
                        <enumerationValue key="default">Default</enumerationValue>
                        <enumerationValue key="never">Never</enumerationValue>
                    </enumerationValues>
                </property>
            </propertyGroup>
            <propertyGroup caption="Minimum value">
                <property key="minimumValue" type="attribute" required="false">
                    <caption>Dynamic minimum value</caption>
                    <description>The minimum value that can be selected.</description>
                    <attributeTypes>
                        <attributeType name="Integer"/>
                        <attributeType name="Long"/>
                        <attributeType name="Decimal"/>
                    </attributeTypes>
                </property>
                <property key="defaultMinimumValue" type="integer" defaultValue="0">
                    <caption>Static minimum value</caption>
                    <description>Used when no dynamic value is provided.</description>
                </property>
            </propertyGroup>
            <propertyGroup caption="Maximum value">
                <property key="maximumValue" type="attribute" required="false">
                    <caption>Dynamic maximum value</caption>
                    <description>The maximum value that can be selected.</description>
                    <attributeTypes>
                        <attributeType name="Integer"/>
                        <attributeType name="Long"/>
                        <attributeType name="Decimal"/>
                    </attributeTypes>
                </property>
                <property key="defaultMaximumValue" type="integer" defaultValue="100">
                    <caption>Static maximum value</caption>
                    <description>Used when no dynamic value is provided.</description>
                </property>
            </propertyGroup>
            <propertyGroup caption="Step size">
                <property key="step" type="attribute" required="false">
                    <caption>Dynamic step size</caption>
                    <description>The interval between two selectable points.</description>
                    <attributeTypes>
                        <attributeType name="Integer"/>
                        <attributeType name="Long"/>
                        <attributeType name="Decimal"/>
                    </attributeTypes>
                </property>
                <property key="defaultStep" type="integer" defaultValue="1">
                    <caption>Static step size</caption>
                    <description>Used when no dynamic value is provided.</description>
                </property>
            </propertyGroup>
        </propertyGroup>
        <propertyGroup caption="Events">
            <property key="onChange" type="action" required="false">
                <caption>On change</caption>
                <description>Called continuously while the user is dragging the handle.</description>
            </property>
            <property key="onChangeComplete" type="action" required="false">
                <caption>On change complete</caption>
                <description>Called when the user releases the handle, regardless of whether the value has changed.</description>
            </property>
        </propertyGroup>
    </properties>
</widget>

=== 2gplus/widgets-resources/packages/video-player/src/VideoPlayer.xml
<?xml version="1.0" encoding="utf-8" ?>
<widget id="com.mendix.widget.native.videoplayer.VideoPlayer" pluginWidget="true" needsEntityContext="true" offlineCapable="true" xmlns="http://www.mendix.com/widget/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mendix.com/widget/1.0/ ../xsd/widget.xsd">
    <name>VideoPlayer</name>
    <description>My widget description</description>
    <icon/>
    <properties>
        <property key="url" type="attribute">
            <caption>Video URL</caption>
            <category>General</category>
            <description>The URL containing the video. Needs to be MP4</description>
            <attributeTypes>
                <attributeType name="String"/>
            </attributeTypes>
        </property>
    </properties>
</widget>
