=== 2gplus/widgets-resources/xsd/widget.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.mendix.com/widget/1.0/"
           xmlns="http://www.mendix.com/widget/1.0/"
           elementFormDefault="qualified">

    <xs:element name="widget" type="widgetType"/>

    <xs:complexType name="widgetType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="icon" type="xs:base64Binary" minOccurs="0"/>
            <xs:element name="phonegap" type="phonegapType" minOccurs="0"/>
            <xs:element name="properties" type="propertiesType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="needsEntityContext" type="xs:boolean" use="required"/>
        <xs:attribute name="pluginWidget" type="xs:boolean"/>
        <xs:attribute name="mobile" type="xs:boolean" default="false"/>
        <xs:attribute name="supportedPlatform" type="platformType" default="All"/>
        <xs:attribute name="offlineCapable" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="phonegapType">
        <xs:attribute name="enabled" type="xs:boolean" use="required"/>
    </xs:complexType>

    <xs:complexType name="propertiesType">
        <xs:choice>
            <xs:sequence>
                <xs:element name="propertyGroup" type="propertyGroupType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="property" type="propertyType" minOccurs="1" maxOccurs="unbounded"/>
                    <xs:element name="systemProperty" type="systemPropertyType" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
            </xs:sequence>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="propertyGroupType">
        <xs:complexContent>
            <xs:extension base="propertiesType">
                <xs:attribute name="caption" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="propertyType">
        <xs:sequence>
            <xs:element name="caption" type="xs:string"/>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="attributeTypes" type="attributeTypesType" minOccurs="0"/>
            <xs:element name="enumerationValues" type="enumerationValuesType" minOccurs="0"/>
            <xs:element name="properties" type="propertiesType" minOccurs="0"/>
            <xs:element name="returnType" type="returnTypeType" minOccurs="0"/>
            <xs:element name="translations" type="translationsType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string" use="required"/>
        <xs:attribute name="type" type="propertyTypeType" use="required"/>
        <xs:attribute name="isList" type="xs:boolean" default="false"/>
        <xs:attribute name="entityProperty" type="xs:string"/>
        <xs:attribute name="allowNonPersistableEntities" type="xs:boolean" default="false"/>
        <xs:attribute name="isPath" type="isPathType" default="no"/>
        <xs:attribute name="pathType" type="pathTypeType"/>
        <xs:attribute name="parameterIsList" type="xs:boolean" default="false"/>
        <xs:attribute name="multiline" type="xs:boolean" default="false"/>
        <xs:attribute name="defaultValue" type="xs:string" default=""/>
        <xs:attribute name="required" type="xs:boolean" default="true"/>
        <xs:attribute name="isDefault" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:simpleType name="propertyTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="action"/>
            <xs:enumeration value="attribute"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="enumeration"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="object"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="textTemplate"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="attributeTypesType">
        <xs:sequence>
            <xs:element name="attributeType" type="attributeTypeType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="attributeTypeType">
        <xs:attribute name="name" type="attributeTypeNameType" use="required"/>
    </xs:complexType>

    <xs:simpleType name="attributeTypeNameType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="AutoNumber"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Currency"/>
            <xs:enumeration value="DateTime"/>
            <xs:enumeration value="Enum"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="HashString"/>
            <xs:enumeration value="Integer"/>
            <xs:enumeration value="Long"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Decimal"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="isPathType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="no"/>
            <xs:enumeration value="optional"/>
            <xs:enumeration value="yes"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="pathTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="reference"/>
            <xs:enumeration value="referenceSet"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="enumerationValuesType">
        <xs:sequence>
            <xs:element name="enumerationValue" type="enumerationValueType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="enumerationValueType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="key" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="returnTypeType">
        <xs:attribute name="type" type="returnTypeTypeType" use="required"/>
        <xs:attribute name="isList" type="xs:boolean" default="false"/>
        <xs:attribute name="entityProperty" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="returnTypeTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Void"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Integer"/>
            <xs:enumeration value="Float"/>
            <xs:enumeration value="DateTime"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Object"/>
            <xs:enumeration value="Decimal"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="translationsType">
        <xs:sequence>
            <xs:element name="translation" type="translationType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="translationType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="platformType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="All"/>
            <xs:enumeration value="Native"/>
            <xs:enumeration value="Web"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="systemPropertyType">
        <xs:sequence>
            <xs:element name="category" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="key" type="systemPropertyKey" use="required"/>
    </xs:complexType>

    <xs:simpleType name="systemPropertyKey">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Label"/>
            <xs:enumeration value="Name"/>
            <xs:enumeration value="TabIndex"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== 2gplus/widgets-resources/packages/range-slider/src/RangeSlider.xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.mendix.widget.native.rangeslider.RangeSlider" supportedPlatform="Native" needsEntityContext="true" offlineCapable="true" pluginWidget="true" xmlns="http://www.mendix.com/widget/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mendix.com/widget/1.0/ ../../../xsd/widget.xsd">
    <name>Range slider</name>
    <description>Change range of values using a slider.</description>
    <icon>iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAAEvQFx7AAAAIVBMVEUAAAD///9SuP+IiIhJsfdJsfhJsfeJiYlIsPhIsPeIiIjzihhCAAAACXRSTlMAARlJZb3I4/MVTrONAAAAz0lEQVRIx2NgQAMTgJhr1qpVEBZOwAmSrZy1agEDB151IMA4E6YJg8Ewk4EqgHMqLiu4Vs5cBQQLsNnOOomB3oAxwwFVIHMmWhDMRBWwWgUUWAUFy7GpwCLgOXMmwwgGLG0CqAKRMyeih9g0AkFISKAKOV4WAwVWkRNRWARmoAtMQRXQnBnAMAqGG2CKnDlzqgIeBcAsjZEUUEAnSMEMPApmggHNFFStAucApEywCjU3mONWUEwvR0JLXIzsjwJEQQoC8cWWSEab42iapQQAAD3okfmgsuelAAAAAElFTkSuQmCC</icon>
    <properties>
        <propertyGroup caption="General">
            <propertyGroup caption="Data source selected range">
                <property key="lowerValueAttribute" type="attribute">
                    <caption>Lower value attribute</caption>
                    <description>The selected lower bound value on the slider.</description>
                    <attributeTypes>
                        <attributeType name="Integer"/>
                        <attributeType name="Long"/>
                        <attributeType name="Decimal"/>
                    </attributeTypes>
                </property>
                <property key="upperValueAttribute" type="attribute">
                    <caption>Upper value attribute</caption>
                    <description>The selected upper bound value on the slider.</description>
                    <attributeTypes>
                        <attributeType name="Integer"/>
                        <attributeType name="Long"/>
                        <attributeType name="Decimal"/>
                    </attributeTypes>
                </property>
            </propertyGroup>
            <propertyGroup caption="Editability">
                <property key="editable" type="enumeration" defaultValue="default">
                    <caption>Editable</caption>
                    <description/>
                    <enumerationValues>
                        <enumerationValue key="default">Default</enumerationValue>
                        <enumerationValue key="never">Never</enumerationValue>
                    </enumerationValues>
                </property>
            </propertyGroup>
            <propertyGroup caption="Minimum range value">
                <property key="minimumValueAttribute" type="attribute" required="false">
                    <caption>Attribute</caption>
                    <description>The minimum value that can be selected.</description>
                    <attributeTypes>
                        <attributeType name="Integer"/>
                        <attributeType name="Long"/>
                        <attributeType name="Decimal"/>
                    </attributeTypes>
                </property>
                <property key="minimumValueDefault" type="integer" defaultValue="0">
                    <caption>Static</caption>
                    <description>Used when no value is provided through the minimum range value attribute.</description>
                </property>
            </propertyGroup>
            <propertyGroup caption="Maximum range value">
                <property key="maximumValueAttribute" type="attribute" required="false">
                    <caption>Attribute </caption>
                    <description>The maximum value that can be selected.</description>
                    <attributeTypes>
                        <attributeType name="Integer"/>
                        <attributeType name="Long"/>
                        <attributeType name="Decimal"/>
                    </attributeTypes>
                </property>
                <property key="maximumValueDefault" type="integer" defaultValue="100">
                    <caption>Static </caption>
                    <description>Used when no value is provided through the maximum range value attribute.</description>
                </property>
            </propertyGroup>
            <propertyGroup caption="Step size">
                <property key="stepSizeAttribute" type="attribute" required="false">
                    <caption>Attribute  </caption>
                    <description>The interval between two selectable points.</description>
                    <attributeTypes>
                        <attributeType name="Integer"/>
                        <attributeType name="Long"/>
                        <attributeType name="Decimal"/>
                    </attributeTypes>
                </property>
                <property key="stepSizeDefault" type="integer" defaultValue="1">
                    <caption>Static  </caption>
                    <description>Used when no value is provided through the step size attribute.</description>
                </property>
            </propertyGroup>
        </propertyGroup>
        <propertyGroup caption="Events">
            <property key="onSlide" type="action" required="false">
                <caption>On slide</caption>
                <description>Called when the value changes while the user is sliding the handle.</description>
            </property>
            <property key="onChange" type="action" required="false">
                <caption>On change</caption>
                <description>Called when the user releases the handle and the value has changed.</description>
            </property>
        </propertyGroup>
    </properties>
</widget>

=== 2gplus/widgets-resources/packages/color-picker/src/ColorPicker.xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.mendix.widget.native.colorpicker.ColorPicker" supportedPlatform="Native" needsEntityContext="true" offlineCapable="true" pluginWidget="true" xmlns="http://www.mendix.com/widget/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mendix.com/widget/1.0/ ../../../node_modules/@mendix/pluggable-widgets-api/widget.xsd">
    <name>Color picker</name>
    <description>Pick a color from a circular color input</description>
    <icon>iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAA5FBMVEUAAACAgIBVVVVgYGBVVVVmZmZdXV1iYmJVVVVeXl5ZWVlVVVVVVVVYWFhJtv9bW1tXV1dMs/pVVVVYWFhJs/hXV1dLtPhWVlZJsvhXV1dWVlZXV1dXV1dVVVVXV1dWVlZWVlZWVlZWVlZVVVVVVVVWVlZIsfdJsfdJsPdJsPhWVlZWVlZVVVVVVVVWVlZVVVVVVVVWVlZWVlZVVVVVVVVVVVVVVVVJsPdVVVVVVVVWVlZJsPdVVVVWVlZIsPdJsfdVVVVIsPdWVlZVVVVJsfhVVVVWVlZVVVVWVlZVVVVIsPdVVVWIl4c0AAAASnRSTlMAAgMICQoLDRITFBUYGhwcLzY2Q0ZGR0dJSUpPVWNkgoOFkpmcoaanqKyytba5vsXGx9bY293e4ODh4uPj5ebo6u3u7/Lz9Pb9/n9E/agAAAExSURBVHgB7dPZTsJAFMbxT0CpWivgIgiKslRxQUQEpbWAssic938fD4wx3KDOaWJC7O/q3Hz/pGkGke+lSs3RqFlKQSZemdLctBKHQKJBXxoJmKvSgiqMZYi1C7ZdaBPLwFSZV60kWLLFZxmmZqu8PvOzFkxNeGXp0+JzAlPEFu+/DUSBnE9L+Dn8hk9L+eED4T9h5X5j1vOyoQKeUl6ogGL/OxAFokCfR7Z+TDaffZiq8+pUP+cTPuswVeRVdxPMeuazCFNbY57d7wI7d3yMt2HsjNjbwd4rsXOYi10Re3wgdh2DwPoNfbrdgMw7aWtY2cCT3r9A6qhLzD+G3GGns48QnKFSQwdyNcVqEEuruTSkLnXgAlI9HehBKtCBAFKuDriQcgaKDRyIOW4QuD/tIx9N6qiDmf0nQgAAAABJRU5ErkJggg==</icon>
    <properties>
        <propertyGroup caption="General">
            <propertyGroup caption="Data source">
                <property key="color" type="attribute">
                    <caption>Color</caption>
                    <description>Attribute containing a valid color like #d0d0d0. Non-code color values such as 'red' are not supported.</description>
                    <attributeTypes>
                        <attributeType name="String"/>
                    </attributeTypes>
                </property>
            </propertyGroup>
            <propertyGroup caption="Events">
                <property key="onChange" type="action" required="false">
                    <caption>On change</caption>
                    <description>Called when the user releases the handle, regardless of whether the value has changed.</description>
                </property>
            </propertyGroup>
            <propertyGroup caption="Common">
                <systemProperty key="Name"/>
            </propertyGroup>
        </propertyGroup>
    </properties>
</widget>

=== 2gplus/widgets-resources/packages/app-events/src/AppEvents.xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.mendix.widget.native.appevents.AppEvents" needsEntityContext="false" offlineCapable="true" pluginWidget="true" xmlns="http://www.mendix.com/widget/1.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mendix.com/widget/1.0/ ../../../xsd/widget.xsd">
    <name>App events</name>
    <description>Perform actions on all kinds of events</description>
    <icon></icon>
    <properties>
        <property key="onLoad" type="action" required="false">
            <caption>On page load</caption>
            <category>Page</category>
            <description>The moment this widget is created.</description>
        </property>

        <property key="onResume" type="action" required="false">
            <caption>On resume</caption>
            <category>App</category>
            <description>The user navigated back to this app.</description>
        </property>
        <property key="onResumeTimeout" type="integer" defaultValue="0">
            <caption>On resume timeout</caption>
            <category>App</category>
            <description>Only call the on resume action, if it was this amount of seconds after the last time the app was resumed (or started).</description>
        </property>

        <property key="onOnline" type="action" required="false">
            <caption>On online</caption>
            <category>Network</category>
            <description>The device network status changed to online.</description>
        </property>
        <property key="onOnlineTimeout" type="integer" defaultValue="5">
            <caption>On online timeout</caption>
            <category>Network</category>
            <description>Only call the on online action, if it was this amount of seconds after the last time the device came online.</description>
        </property>

        <property key="timeouts" type="object" isList="true" required="false">
            <caption>Timers</caption>
            <category>Time</category>
            <description>Call an action after the timer completes.</description>
            <properties>
                <property key="timeout" type="integer" defaultValue="30">
                    <caption>Time</caption>
                    <category>Timer</category>
                    <description>How many seconds should pass before the action is called.</description>
                </property>
                <property key="placeholderForModelerBug1" type="string" required="false">
                    <caption>Ignore me</caption>
                    <category>Ignore me</category>
                    <description/>
                </property>
                <property key="placeholderForModelerBug2" type="string" required="false">
                    <caption>Ignore me too</caption>
                    <category>Ignore me</category>
                    <description/>
                </property>
                <property key="action" type="action" required="true">
                    <caption>Action</caption>
                    <category>Timer</category>
                    <description></description>
                </property>
            </properties>
        </property>
        <property key="intervals" type="object" isList="true" required="false">
            <caption>Intervals</caption>
            <category>Time</category>
            <description>Call an action based on an interval, until this widget is destroyed.</description>
            <properties>
                <property key="interval" type="integer" defaultValue="30">
                    <caption>Interval</caption>
                    <category>Interval</category>
                    <description>Defines how often the action is called, in seconds.</description>
                </property>
                <property key="placeholderForModelerBug1" type="string" required="false">
                    <caption>Ignore me</caption>
                    <category>Ignore me</category>
                    <description/>
                </property>
                <property key="placeholderForModelerBug2" type="string" required="false">
                    <caption>Ignore me too</caption>
                    <category>Ignore me</category>
                    <description/>
                </property>
                <property key="action" type="action" required="true">
                    <caption>Action</caption>
                    <category>Interval</category>
                    <description></description>
                </property>
            </properties>
        </property>
    </properties>
</widget>

=== 2gplus/widgets-resources/packages/progress-circle/src/ProgressCircle.xml
<?xml version="1.0" encoding="utf-8"?>
<widget id="com.mendix.widget.native.progresscircle.ProgressCircle" needsEntityContext="true" offlineCapable="true" pluginWidget="true" 
    xmlns="http://www.mendix.com/widget/1.0/" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mendix.com/widget/1.0/ ../../../xsd/widget.xsd">
    <name>Progress circle</name>
    <description>Displays progress in a circle.</description>
    <icon>iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAACIlBMVEUAAAD///9VVVUzZpkzmZlmZmZVVVVgYGBVVVVVjqpmZmZVVVViYmJLh6VLtP9aWlpVVVVeXl5Jtv9OTk5OhaZcXFxOsf9Ktf9YWFhVVVVcXFxYWFhXV1dVVVVOfaBShqRVVVVXV1dVVVVXV1dXV1dWVlZRe5pPgKBQfZ1WVlZVVVVXV1dWVlZVVVVWVlZQfJlWVlZRe5lWVlZVVVVWVlZWVlZQeJJVVVVWVlZRdIxVVVVWVlZVVVVRdY9VVVVVVVVSdo9VVVVVVVVSdIpWVlZWVlZVVVVKqupJsPhSboFVVVVVVVVJsPhScIRSboRJsPhVVVVWVlZWVlZSbH1SbH5UVFRVVVVSantVVVVVVVVSZXJVVVVVVlhWVlZSbH5TZXJUVFRTZXFTZ3RVVVVWVlZUXWRVXGJWVlZSdIxTZnRUW2BXV1dUWl5UXGFVVVVOjLdVVVVTYm1VXmRVX2ZOh61PiK5TYmxVVVVVWFpWWFpUXGFUYGhVVVVWWFpWWVpLl8tTX2hTYWhUWl5Rb4VTXWRUYGhVVVVVWlxScIVUXGFUXGJUXWNVVVVWVlZUVldUV1hUWV1UX2dVVVVVVVZVWVxIrfJIrfNIrvVIsPdJo+BJp+dJqetJqexJq+5JrO9JrfFLlslLl8pLntZMk8RNh65NjbhOh65OiLBPeZVPgaRQdpBQd5FRcIZSaHhTXmZTX2ZTaXpUVlZUWFpUWFtUW2BVVVXVGoP9AAAAlXRSTlMAAQMFBQUGCAkJCgwNEREREhMVFxcZGh8gJCQ0NTY7O0VGSElPUFteYGJjcHFyeX2DhYWZmpufn6Oqq6ywsbGzuL3CxMbHyMvP0NLV1tbX3N7f4uPj4+Tm5+nr7Ozu7+/v8PDw8vPz8/T09PT19fX29vf39/j4+Pn5+fr6+vr6+/v7+/z8/Pz8/f39/f39/v7+/v7+/uRWljcAAAOKSURBVHja7Vf5P1RRFB8lESqNKaRlJkqMvWgjg1al7EpJirKNqMhSKlqmEk3hMWVNyFKW9/91z73jznuvd8L79KPvT+ee8865957tnqdbB44NwZFHUrOKGj++fHj9wvGDG9emvSnkxB1Rhu6cWK9Vq3tGFYkqsKX4ru7s4fkigo4E95X1D2SIDA+SI0yBfh69jv7hiZkFJ7MhegV1tzj24c3E0C2MI1AMjU0vMUma27/0vU+JAGuMD2cJyxicWqTCAn9cP+AifPE63iDhCS4MTM6DvG4fqn8N5Pm7ZUxBitE5+OIdYsGb7n8WtscMCAOz9Az+qv6j9z+2mTO2m9Pzqjo/f/n1+4eDW+j5Sf2g5sk4qs+Xh7PtIof90zg3QS2kqcSfnn95//2FogLvR5bPQG8R/Vf+ZYD/DM7FaVEFb/ucfgBPNihzMhzi5/T/tqtMw2oxG/V6o9liZetXX52xgGgmKOoH8j/eqX9XBOSZXGJTHmW9cVqYhLqQV1YUbGhg56f7t4YrTtgK3Bd97BKQkymy+of6jWE0vX9JkNJJQSXAbxcopqC6pf0hBOrHh/mf6nuqdAlqgcXiG1RWrER4kqwTGVkI52f7K88At2gWKKYJmSOJIfSvUJY/sA2/vzJSBCyjxqDLuSK5B/oHq/9s8L8OAcSinvUH6DCHuCCSrJJZ/kP+mjADJshqVhczhEzigqNkFcFNWXUoIKO+UwMThMrk/FS+7RlCWXADFiKuoAaGCVXK+VlkFchvacYNmIm4hhroJ1QL50Ma+VGqilBG3ICRiJ9RAw5IJc5vJCsPSnUSSo8b0IMXqYFeQnWpGPhAKANuwCA3oO0KTa4raHNipcuJKmFMXzmMt1xh1JZIj3kiXf5/qRy8hmIqlxSTpnKulZSzloZSLWkomlpaG3vqaUvT0lSLpU1VQ1svk7Z1/GG5hz0sT2QPC/q0bT33XP1pK5M9bejjuuO80NcuqqBY/rhiz/vOS/DRSLNSvbpN/rxjA8auK87vxuulA0Z5rWLAQEec+z38S8f3ipqndntT5e1HKiMOOmTNDggI0CGLI+AGSOdGcX0+5iHYWwfy+UnkEPigyeFfIAIWpwa5FjLqYnBLEymWpseGmB4ybOOIbhAZFmYmhvsdvdi4j8M9oUPjDweHb4pN4y8Ph1dsbrfipysX+enCbxKWlFnaYuvqsrWUZiaFuevWgeIPYH/Yqk16GocAAAAASUVORK5CYII=</icon>
    <properties>
        <property key="indeterminate" type="boolean" defaultValue="false">
            <caption>Indeterminate</caption>
            <category>Value</category>
            <description>If set, the indicator will spin and the progress value will be ignored</description>
        </property>
        <property key="progressValue" type="attribute" required="false">
            <caption>Progress value</caption>
            <category>Value</category>
            <description/>
            <attributeTypes>
                <attributeType name="Integer" />
                <attributeType name="Long" />
                <attributeType name="Decimal" />
            </attributeTypes>
        </property>
        <property key="progressMax" type="attribute" required="false">
            <caption>Maximum progress value</caption>
            <category>Value</category>
            <description>Defaults to 100</description>
            <attributeTypes>
                <attributeType name="Integer" />
                <attributeType name="Long" />
                <attributeType name="Decimal" />
            </attributeTypes>
        </property>

        <property key="animated" type="boolean" defaultValue="true">
            <caption>Animated</caption>
            <category>Appearance</category>
            <description>Whether or not to animate changes to the progress value</description>
        </property>
        <property key="size" type="integer" defaultValue="40">
            <caption>Diameter</caption>
            <category>Appearance</category>
            <description />
        </property>
        <property key="thickness" type="integer" defaultValue="3">
            <caption>Thickness</caption>
            <category>Appearance</category>
            <description />
        </property>
        <property key="showsText" type="boolean" defaultValue="false">
            <caption>Show progress text</caption>
            <category>Appearance</category>
            <description />
        </property>
        <property key="color" type="string" required="false">
            <caption>Fill color</caption>
            <category>Appearance</category>
            <description/>
        </property>
        <property key="unfilledColor" type="string" required="false">
            <caption>Unfilled color</caption>
            <category>Appearance</category>
            <description/>
        </property>
        <property key="borderWidth" type="integer" defaultValue="1">
            <caption>Border width</caption>
            <category>Appearance</category>
            <description>Set 0 to remove</description>
        </property>
        <property key="borderColor" type="string" required="false">
            <caption>Border color</caption>
            <category>Appearance</category>
            <description/>
        </property>
    </properties>
</widget>
